ALTER TABLE MOUNTAINS DROP COLUMN FIRST_ASCENT;
ALTER TABLE MOUNTAINS DROP COLUMN ASCENTS_BEF_2004;
ALTER TABLE MOUNTAINS DROP COLUMN FAILED_ATTEMPTS_BEF_2004;
ALTER TABLE MOUNTAINS DROP COLUMN MOUTAIN_IMAGE;
